-- =====================================================================
-- Lualua Crochet & Knitting — Production CRM
-- Migration 0001: Core schema
-- =====================================================================
-- Run order: 0001_schema -> 0002_functions_triggers -> 0003_rls -> 0004_storage
-- =====================================================================

-- Extensions ----------------------------------------------------------
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- ENUM TYPES
-- ---------------------------------------------------------------------
do $$ begin
  create type user_role as enum ('admin', 'staff');
exception when duplicate_object then null; end $$;

do $$ begin
  create type customer_type as enum ('new_lead', 'active', 'inactive');
exception when duplicate_object then null; end $$;

do $$ begin
  create type product_category as enum ('knitwear', 'crochet', 'accessories');
exception when duplicate_object then null; end $$;

do $$ begin
  create type project_status as enum (
    'inquiry', 'quotation', 'sampling', 'sample_revision', 'waiting_po',
    'production', 'quality_control', 'ready_shipment', 'shipped',
    'completed', 'cancelled'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type po_status as enum ('draft', 'received', 'confirmed', 'completed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type shipment_status as enum ('pending', 'in_transit', 'delivered');
exception when duplicate_object then null; end $$;

do $$ begin
  create type file_folder as enum (
    'design_files', 'photos', 'tech_packs', 'po', 'invoices',
    'shipping_documents', 'sample_photos', 'qc_reports'
  );
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------
-- USERS  (profile mirror of auth.users — never store passwords here)
-- ---------------------------------------------------------------------
create table if not exists public.users (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null,
  full_name   text,
  role        user_role not null default 'staff',
  avatar_url  text,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- CUSTOMERS
-- ---------------------------------------------------------------------
create table if not exists public.customers (
  id              uuid primary key default gen_random_uuid(),
  customer_name   text not null,
  company_name    text,
  country         text,
  contact_person  text,
  email           text,
  phone           text,
  whatsapp        text,
  website         text,
  customer_type   customer_type not null default 'new_lead',
  notes           text,
  assigned_to     uuid references public.users(id) on delete set null,
  created_by      uuid references public.users(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_customers_name    on public.customers (customer_name);
create index if not exists idx_customers_country on public.customers (country);
create index if not exists idx_customers_type    on public.customers (customer_type);

-- ---------------------------------------------------------------------
-- PROJECTS
-- project_number is auto-generated by trigger (see 0002).
-- ---------------------------------------------------------------------
create table if not exists public.projects (
  id               uuid primary key default gen_random_uuid(),
  customer_id      uuid not null references public.customers(id) on delete cascade,
  project_number   text unique,
  project_name     text not null,
  product_category product_category,
  collection_name  text,
  quantity         integer,
  target_price     numeric(12,2),
  currency         text default 'USD',
  sampling_date    date,
  production_date  date,
  shipping_date    date,
  status           project_status not null default 'inquiry',
  assigned_to      uuid references public.users(id) on delete set null,

  -- Production tracking (1:1 with project)
  yarn_type         text,
  yarn_supplier     text,
  gauge             text,
  machine_type      text,
  production_start  date,
  production_end    date,
  progress          integer not null default 0 check (progress between 0 and 100),
  production_notes  text,

  created_by  uuid references public.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists idx_projects_customer on public.projects (customer_id);
create index if not exists idx_projects_status   on public.projects (status);
create index if not exists idx_projects_name     on public.projects (project_name);

-- Specifications (free-form key/value rows per project)
create table if not exists public.project_specs (
  id          uuid primary key default gen_random_uuid(),
  project_id  uuid not null references public.projects(id) on delete cascade,
  label       text not null,
  value       text,
  sort_order  integer default 0,
  created_at  timestamptz not null default now()
);
create index if not exists idx_specs_project on public.project_specs (project_id);

-- ---------------------------------------------------------------------
-- FILES  (documents + photos all live here, grouped by folder enum)
-- version_group groups successive versions of the same logical file.
-- ---------------------------------------------------------------------
create table if not exists public.project_files (
  id             uuid primary key default gen_random_uuid(),
  project_id     uuid references public.projects(id) on delete cascade,
  customer_id    uuid references public.customers(id) on delete cascade,
  folder         file_folder not null default 'design_files',
  file_name      text not null,
  storage_path   text not null,          -- path inside the 'crm-files' bucket
  mime_type      text,
  size_bytes     bigint,
  version        integer not null default 1,
  version_group  uuid not null default gen_random_uuid(),
  is_current     boolean not null default true,
  uploaded_by    uuid references public.users(id) on delete set null,
  created_at     timestamptz not null default now()
);
create index if not exists idx_files_project on public.project_files (project_id);
create index if not exists idx_files_folder  on public.project_files (folder);
create index if not exists idx_files_group   on public.project_files (version_group);

-- ---------------------------------------------------------------------
-- PURCHASE ORDERS
-- ---------------------------------------------------------------------
create table if not exists public.purchase_orders (
  id           uuid primary key default gen_random_uuid(),
  project_id   uuid not null references public.projects(id) on delete cascade,
  customer_id  uuid references public.customers(id) on delete set null,
  po_number    text,
  po_date      date,
  file_id      uuid references public.project_files(id) on delete set null,
  quantity     integer,
  unit_price   numeric(12,2),
  total_amount numeric(14,2),
  currency     text default 'USD',
  status       po_status not null default 'draft',
  created_by   uuid references public.users(id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists idx_po_project on public.purchase_orders (project_id);

-- ---------------------------------------------------------------------
-- SHIPMENTS
-- ---------------------------------------------------------------------
create table if not exists public.shipments (
  id                  uuid primary key default gen_random_uuid(),
  project_id          uuid not null references public.projects(id) on delete cascade,
  customer_id         uuid references public.customers(id) on delete set null,
  shipping_date       date,
  courier             text,
  tracking_number     text,
  invoice_file_id     uuid references public.project_files(id) on delete set null,
  packing_list_file_id uuid references public.project_files(id) on delete set null,
  destination_country text,
  status              shipment_status not null default 'pending',
  created_by          uuid references public.users(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists idx_shipments_project on public.shipments (project_id);

-- ---------------------------------------------------------------------
-- NOTES  (attach to a customer and/or a project)
-- ---------------------------------------------------------------------
create table if not exists public.notes (
  id           uuid primary key default gen_random_uuid(),
  customer_id  uuid references public.customers(id) on delete cascade,
  project_id   uuid references public.projects(id) on delete cascade,
  body         text not null,
  attachment_file_id uuid references public.project_files(id) on delete set null,
  created_by   uuid references public.users(id) on delete set null,
  created_at   timestamptz not null default now()
);
create index if not exists idx_notes_customer on public.notes (customer_id);
create index if not exists idx_notes_project  on public.notes (project_id);
-- Full-text-ish search support for note bodies
create index if not exists idx_notes_body_trgm on public.notes using gin (to_tsvector('simple', coalesce(body,'')));

-- ---------------------------------------------------------------------
-- ACTIVITIES  (automatic timeline)
-- ---------------------------------------------------------------------
create table if not exists public.activities (
  id           uuid primary key default gen_random_uuid(),
  customer_id  uuid references public.customers(id) on delete cascade,
  project_id   uuid references public.projects(id) on delete cascade,
  actor_id     uuid references public.users(id) on delete set null,
  action       text not null,          -- e.g. 'uploaded_file', 'updated_status'
  description  text not null,          -- human-readable line
  meta         jsonb,
  created_at   timestamptz not null default now()
);
create index if not exists idx_activities_customer on public.activities (customer_id, created_at desc);
create index if not exists idx_activities_project  on public.activities (project_id, created_at desc);
create index if not exists idx_activities_created  on public.activities (created_at desc);

-- ---------------------------------------------------------------------
-- NOTIFICATIONS  (in-app, per user)
-- ---------------------------------------------------------------------
create table if not exists public.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.users(id) on delete cascade,
  title       text not null,
  body        text,
  link        text,                    -- in-app route, e.g. /projects/<id>
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);
create index if not exists idx_notifications_user on public.notifications (user_id, is_read, created_at desc);
